sudo: required
services:
  - docker

before_install:
  - docker build -t adityasarin16/react-test -f ./client/Dockerfile.dev ./client

after_success:
  - docker build -t adityasarin16/multi-client ./client
  - docker build -t adityasarin16/multi-nginx ./nginx
  - docker build -t adityasarin16/multi-server ./server
  - docker build -t adityasarin16/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push adityasarin16/multi-client
  - docker push adityasarin16/multi-nginx
  - docker push adityasarin16/multi-server
  - docker push adityasarin16/multi-worker
